version: '2'

services:
  api:
    build: ./
    command: gunicorn -b 0.0.0.0 server:API
    volumes:
      - "./:/code/"
    environment:
      - QUEUE_NAME=queue_name
      - QUEUE_ERROR_NAME=queue_error_name
      - QUEUE_TYPE=redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - AWS_ACCESS_KEY_ID=<your key>
      - AWS_SECRET_ACCESS_KEY=<your key>
      - AWS_DEFAULT_REGION=us-east-1
    ports:
      - 8000:8000
    depends_on:
      - solr
      - redis
    links:
      - solr
      - redis

  worker:
    build: ./
    command: python worker.py
    volumes:
      - "./:/code/"
    environment:
      - QUEUE_NAME=queue_name
      - QUEUE_ERROR_NAME=queue_error_name
      - QUEUE_TYPE=redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SOLR_URL=http://solr:8983
      - AWS_ACCESS_KEY_ID=<your key>
      - AWS_SECRET_ACCESS_KEY=<your key>
      - AWS_DEFAULT_REGION=us-east-1
    depends_on:
      - solr
      - redis
    links:
      - solr
      - redis

  redis:
    image: redis
    ports:
      - 6379

  solr:
    image: solr
    ports:
      - 8983:8983
    volumes:
      - ./solr-data:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - commoncrawl
