version: '2'

services:
  api:
    build: ./
    command: gunicorn -b 0.0.0.0 server:api
    volumes:
      - "./:/code/"
    environment:
      - REDIS_HOST=redis
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - solr
    links:
      - redis
      - solr

  worker:
    build: ./
    command: python worker.py
    volumes:
      - "./:/code/"
    environment:
      - REDIS_HOST=redis
      - SOLR_URL=http://solr:8983
    depends_on:
      - redis
      - solr
    links:
      - redis
      - solr

  solr:
    image: solr
    ports:
      - 8983:8983
    volumes:
      - ./solr-data:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - common-crawl

  redis:
    image: redis
    ports:
      - "6379:6379"
